---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: silk-version
  - name: cf-networking-release-ci
  - name: cf-networking-deployments
  - name: silk-tarball
  - name: silk

outputs:
  - name: final-release
  - name: release

run:
  path: cf-networking-release-ci/ci/tasks/silk-shipit
