---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: variables

params:
    ENVIRONMENT_TAG: ~
    DATADOG_API_KEY: ~
    SLI_ORG: ~
    SLI_SPACE: ~
    SLI_APP_NAME: ~

run:
  path: cf-networking-release-ci/ci/tasks/smoke-tests
