---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy-light

inputs:
  - name: cf-networking
  - name: test-config
  - name: vars-store

params:
  ENVIRONMENT_NAME: ~

run:
  path: cf-networking/ci/tasks/test-acceptance-sd
