---
name: cf_networking_local_only

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: cf-networking
    version: latest
  - name: garden-runc
    version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: garden
  instances: 1
  azs: [z1]
  vm_type: basic
  stemcell: trusty
  networks: [{name: shared}]
  jobs:
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        network_plugin: /var/vcap/packages/runc-cni/bin/garden-external-networker
        network_plugin_extra_args:
        - --configFile=/var/vcap/jobs/garden-cni/config/adapter.json
  - name: garden-cni
    release: cf-networking
    properties:
      cf_networking:
        garden_external_networker:
          cni_plugin_dir: /var/vcap/packages/runc-cni/bin
          cni_config_dir: /var/vcap/jobs/garden-cni/config/cni

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
