---
releases:
  - <<: (( merge ))
  - name: netman
    version: latest

properties:
  <<: (( merge ))
  system_domain: (( merge ))
  garden:
    <<: (( merge ))
    network_plugin: /var/vcap/packages/runc-cni/bin/guardian-cni-adapter
    network_plugin_extra_args:
    - --configFile=/var/vcap/jobs/garden-cni/config/adapter.json
  garden-cni:
    adapter:
      cni_plugin_dir: /var/vcap/packages/flannel/bin
      cni_config_dir: /var/vcap/jobs/cni-flannel/config/cni
      netman_url: http://127.0.0.1:4007
  cni-flannel:
    etcd_endpoints:
      - http://netman-db.service.cf.internal:4001
  netman-cf-acceptance: (( merge ))
  netman-agent:
    policy_server_url: http://policy-server.service.cf.internal:4002
  policy-server:
    <<: (( merge ))
    database_password: (( merge ))
    database:
      db_scheme: postgres
      port: 5432
      databases:
      - name: policy_server
        tag: whatever
      roles:
      - name: policy_server
        password: (( .properties.policy-server.database_password ))
        tag: admin
    server:
      <<: (( merge ))
      uaa_client_secret: (( .properties.uaa.clients.network-policy.secret ))
      uaa_url: (( "https://uaa." .properties.system_domain ))
      skip_ssl_validation: (( .properties.diego.ssl.skip_cert_verify ))
      database:
         <<: (( merge ))
         host: (( merge || "policy-server-db.service.cf.internal" ))
         password: (( .properties.policy-server.database_password ))
  uaa:
    clients:
      network-policy:
        secret: (( merge ))

jobs:
- name: database_z1
  <<: (( merge ))
- name: database_z2
  <<: (( merge ))
- name: database_z3
  <<: (( merge ))

- name: policy-server-db
  instances: 1
  persistent_disk: 256
  templates:
  - name: postgres
    release: netman
  - name: consul_agent
    release: cf
  resource_pool: database_z1
  networks:
    - name: diego1
  properties:
    consul:
      agent:
        services:
          policy-server-db:
            name: policy-server-db
            check:
              interval: 5s
              script: /bin/true

- name: policy-server
  instances: 1
  persistent_disk: 256
  templates:
  - name: policy-server
    release: netman
  - name: route_registrar
    release: cf
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  resource_pool: database_z1
  networks:
    - name: diego1
  properties:
    nats: (( .properties.diego.route_emitter.nats ))
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: policy-server
        port: 4002
        registration_interval: 20s
        uris:
        - (( "api." .properties.system_domain "/networking" || "api.bosh-lite.com/networking" ))
    consul:
      agent:
        services:
          policy-server:
            name: policy-server
            check:
              interval: 5s
              script: /bin/true

- name: flannel_etcd
  instances: 1
  networks:
  - name: diego1
  persistent_disk: 256
  resource_pool: database_z1
  templates:
  - name: consul_agent
    release: cf
  - name: etcd
    release: etcd
  properties:
    etcd:
      require_ssl: false
      peer_require_ssl: false
      machines:
      - netman-db.service.cf.internal
    consul:
      agent:
        services:
          netman-db:
            name: netman-db
            check:
              interval: 5s
              script: /bin/true

- name: brain_z1
  <<: (( merge ))
- name: cell_z1
  <<: (( merge ))
  templates:
  - <<: (( merge ))
  - name: garden-cni
    release: netman
  - name: cni-flannel
    release: netman
  - name: netman-agent
    release: netman
  - name: netmon
    release: netman
  - name: natman
    release: netman
- name: cc_bridge_z1
  <<: (( merge ))
- name: route_emitter_z1
  <<: (( merge ))
- name: access_z1
  <<: (( merge ))

- name: brain_z2
  <<: (( merge ))
- name: cell_z2
  <<: (( merge ))
  templates:
  - <<: (( merge ))
  - name: garden-cni
    release: netman
  - name: cni-flannel
    release: netman
  - name: netman-agent
    release: netman
  - name: netmon
    release: netman
  - name: natman
    release: netman
- name: cc_bridge_z2
  <<: (( merge ))
- name: route_emitter_z2
  <<: (( merge ))
- name: access_z2
  <<: (( merge ))

- name: brain_z3
  <<: (( merge ))
- name: cell_z3
  <<: (( merge ))
  templates:
  - <<: (( merge ))
  - name: cni-flannel
    release: netman
- name: cc_bridge_z3
  <<: (( merge ))
- name: route_emitter_z3
  <<: (( merge ))
- name: access_z3
  <<: (( merge ))

- <<: (( merge ))

- name: netman-cf-acceptance
  instances: 1
  lifecycle: errand
  networks:
  - name: diego1
  resource_pool:
    database_z1
  templates:
  - name: netman-cf-acceptance
    release: netman

<<: (( merge ))
