---
releases:
  - <<: (( merge ))
  - name: netman
    version: latest

properties:
  <<: (( merge ))
  system_domain: (( merge ))
  garden:
    <<: (( merge ))
    network_plugin: /var/vcap/packages/runc-cni/bin/garden-external-networker
    network_plugin_extra_args:
    - --configFile=/var/vcap/jobs/garden-cni/config/adapter.json
  natman:
    garden_address: (( diego.executor.garden.address || "/var/vcap/data/garden/garden.sock" ))
    garden_protocol: (( diego.executor.garden.network || "unix" ))
  garden-cni:
    cni_plugin_dir: /var/vcap/packages/runc-cni/bin
    cni_config_dir: /var/vcap/jobs/garden-cni/config/cni

jobs:
- name: database_z1
  <<: (( merge ))
- name: database_z2
  <<: (( merge ))
- name: database_z3
  <<: (( merge ))



- name: brain_z1
  <<: (( merge ))
- name: cell_z1
  <<: (( merge ))
  templates:
  - <<: (( merge ))
  - name: garden-cni
    release: netman
  - name: natman
    release: netman
- name: cc_bridge_z1
  <<: (( merge ))
- name: route_emitter_z1
  <<: (( merge ))
- name: access_z1
  <<: (( merge ))

- name: brain_z2
  <<: (( merge ))
- name: cell_z2
  <<: (( merge ))
  templates:
  - <<: (( merge ))
  - name: garden-cni
    release: netman
  - name: natman
    release: netman
- name: cc_bridge_z2
  <<: (( merge ))
- name: route_emitter_z2
  <<: (( merge ))
- name: access_z2
  <<: (( merge ))

- name: brain_z3
  <<: (( merge ))
- name: cell_z3
  <<: (( merge ))
- name: cc_bridge_z3
  <<: (( merge ))
- name: route_emitter_z3
  <<: (( merge ))
- name: access_z3
  <<: (( merge ))

- <<: (( merge ))

<<: (( merge ))
